---
# tasks file for appserver
- name: 'update website from the git repository'
  git:
    repo: "https://github.com/palbarto/cicd02-starter"
    dest: "{{ install_dir }}"
    single_branch: true
    version: deploy
- name: 'install the nginx.conf file on to the remote machine'
  template:
    src: nginx-server.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
